### ISSUE TITLE
[Bug] CCE supression working too often

### ISSUE THREAD

**Issue by Notoriousi** [ForwarD-NerN/AntiShadowPatch#1]
CCE update suppression seems to apply whenever it shouldn't. 

Recreate:
Step 1: place comparator
Step 2: Make comparator check a (white?) shulker
Step 3: Its using CCE, try opening the shulker, the server would crash (even with NotSoShadowExtras's crash fix)

If you place the comparator after placing the shulker you'd crash as well.

Crashlog:
[crash-2023-11-23_13.16.10-server.txt](https://github.com/ForwarD-NerN/AntiShadowPatch/files/13449743/crash-2023-11-23_13.16.10-server.txt)

**Comment by ForwarD-NerN** [comment]
Hello, thanks for reporting the issue! I somehow missed the Github notification about it and only found out now.
Looking at the crash report, you've caused a block update, not in a player phase. I don't think it's because of my mod, maybe it's another mod causing the issue or some random block update? If you can reproduce it only with the latest version of AntiShadowPatch enabled, please let me know.

Also, thanks for providing the crash report. I found another issue with the CCE suppressor in my mod. Fixed it in 1.0.6.

**Comment by Notoriousi** [comment]
I think this was caused by another mod, unsure what one. Unable to replicate this using only your mods installed. Closing because of a false report.
